name: Code Review Automation

on:
  pull_request:
    branches: [ main, develop ]
  pull_request_review:
    types: [submitted]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests on PR
      run: npm test
      
    - name: Code quality check
      run: |
        echo "Running code quality analysis..."
        npx eslint . --ext .js,.jsx,.ts,.tsx --format json > eslint-report.json || true
        echo "Code quality check completed"
        
    - name: Security scan
      run: |
        npm audit --audit-level moderate
        echo "Security audit completed"
        
    - name: Size analysis
      run: |
        echo "Checking bundle size impact..."
        du -sh . || echo "Size check completed"
        
    - name: Upload review artifacts
      uses: actions/upload-artifact@v3
      with:
        name: code-review-reports
        path: |
          eslint-report.json
          coverage/
        retention-days: 30
        
    - name: PR status update
      run: |
        echo "Code review automation completed"
        echo "All checks passed for PR: ${{ github.event.pull_request.number }}"
