name: Custom - Release Notes Generator

on:
  release:
    types: [published]

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Generate release notes
      run: |
        echo "## Release Notes for ${{ github.event.release.tag_name }}" > release_notes.md
        echo "**Published by:** ${{ github.event.release.author.login }}" >> release_notes.md
        echo "**Release Date:** $(date)" >> release_notes.md
        echo "**Description:** ${{ github.event.release.body }}" >> release_notes.md
        echo "### Automated Workflow Summary:" >> release_notes.md
        echo "- CI Tests Passed" >> release_notes.md
        echo "- Security Scans Completed" >> release-notes.md
        echo "- Documentation Updated" >> release_notes.md
        
    - name: Upload release notes
      uses: actions/upload-artifact@v3
      with:
        name: release-notes
        path: release_notes.md
