name: Deployment Pipeline

on:
  push:
    branches: [ main ]
  release:
    types: [published]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Vercel CLI
      run: npm install --global vercel@32.5.2
      
    - name: Deploy to Vercel Preview
      run: |
        vercel --token ${{ secrets.VERCEL_TOKEN }} --yes
        vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        
    - name: Store deployment URL
      run: |
        echo "DEPLOYMENT_URL=https://heavens-above-git-main-${{ github.repository_owner }}.vercel.app" >> $GITHUB_ENV
        
    - name: Deployment success notification
      run: |
        echo "Application deployed successfully to Vercel"
        echo "URL: https://heavens-above-git-main-${{ github.repository_owner }}.vercel.app"
        echo "Deployment completed at: $(date)"
        
  deploy-production:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Vercel Production
      run: |
        npm install --global vercel@32.5.2
        vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes --confirm
