name: Deploy Documentation
on:
  push:
    branches: [main]
    paths: ['docs/**']
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        run: |
          mkdir -p docs
          echo "# Heavens Above Documentation" > docs/index.md
          echo "Automatically deployed via GitHub Actions" >> docs/index.md
