name: Documentation Deployment
on:
  push:
    branches: [main]
  workflow_dispatch:  # ADD THIS LINE

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs
        run: |
          mkdir -p _site
          echo "<h1>Documentation</h1>" > _site/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
